name: Update Commit Count

on:
  schedule:
    - cron: '0 0 * * *' # Runs once every day at midnight
  workflow_dispatch:

jobs:
  update-commit-count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch commit count for all branches
      run: |
        for branch in $(git branch -r | grep -v '\->'); do
            commit_count=$(git rev-list --count $branch)
            echo "Branch: $branch, Commits: $commit_count" >> commit_counts.txt
        done

    - name: Update README
      run: |
        echo "### Commit Activity Across All Branches" >> README.md
        cat commit_counts.txt >> README.md
        git config --global user.name "GitHub Action"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update commit counts"
        git push
